name: Unreal 4.27 Development Build

on:
  push:
    branches:
      - main
    paths-ignore:
      - README.md
    tags:
      - "v*.*.*"
  pull_request:
    paths-ignore:
      - README.md

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3

    - name: Setup
      run: |
        sudo chmod 777 $GITHUB_WORKSPACE
        sudo rm -rf /usr/share/dotnet
        sudo rm -rf /opt/ghc
        sudo rm -rf "/usr/local/share/boost"
        sudo rm -rf "$AGENT_TOOLSDIRECTORY"
        sudo rm -rf /usr/local/lib/android
        make

    - uses: addnab/docker-run-action@v3
      with:
        registry: ghcr.io
        username: ${{ secrets.USER }}
        password: ${{ secrets.PAT }}
        image: ghcr.io/epicgames/unreal-engine:dev-slim-4.27.2
        options: -v ${{ github.workspace }}:/home/ue4/play-unreal-plugin -e HOME=/home/ue4
        run: |
          cd ~/play-unreal-plugin
          make RunUAT
